GameCollectibles/GameCollectibleApp/Models/GameViewModel.cs
using GameCollectiblesCore.Games;
namespace GameCollectibleApp.Models
{
    public class GameViewModel
    {
        public Game? game { get; set; }
        public int? gameID { get; set; }
        public string gameTitle { get; set; }
        public string gameDescription { get; set; }
        public IEnumerable<GameCollectiblesCore.Categories.Category>? categories { get; set; }
        public string? SelectedUserName { get; set; }
        public string? errorMessage { get; set; }
    }
}

GameCollectibles/GameCollectibleApp/Controllers/CategoriesController.cs
using GameCollectibleApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Data.Sql;
using GameCollectiblesCore.Categories;
using GameCollectiblesData.Categories;
using GameCollectiblesCore.Games;
using GameCollectiblesData.Games;

namespace GameCollectibleApp.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly string _connectionString;
        private readonly CategoryService _categoryService;
        private readonly ILogger<HomeController> _logger;

        public CategoriesController(IConfiguration configuration, ILogger<HomeController> logger)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
            _categoryService = new CategoryService(new CategoryRepository(_connectionString), new GameRepository(_connectionString));
            _logger = logger;
        }

        public IActionResult Index([FromQuery] int categoryID)
        {
            return View();
        }

        public IActionResult Create([FromQuery]int GameID, string errMessage)
        {
            var model = new CategoryViewModel{
                gameID = GameID,
                errorMessage = errMessage
            };
            return View(model);
        }

        public ActionResult AddCategory(CategoryViewModel categoryVM)
        {
            Category category = new Category(categoryVM.gameID ?? default(int), categoryVM.categoryID ?? default(int), categoryVM.categoryName);


            try
            {
                _categoryService.createCategory(category);
                return RedirectToAction("Game", "Games", new { gameID = category.gameID });
            }
            catch (System.Exception)
            {
                // ik doe er niks mee
                throw;
            }
            
        }
        


    }
}

GameCollectibles/GameCollectibleApp/Controllers/CollectiblesController.cs
using GameCollectibleApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Data.Sql;
using GameCollectiblesCore.Collectibles;
using GameCollectiblesData.Collectibles;

namespace GameCollectibleApp.Controllers
{
    public class CollectiblesController : Controller
    {
        private readonly string _connectionString;
        private readonly CollectibleService _collectibleService;
        private readonly ILogger<HomeController> _logger;

        public CollectiblesController(IConfiguration configuration, ILogger<HomeController> logger)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
            _collectibleService = new CollectibleService(new CollectibleRepository(_connectionString), new GameCollectiblesData.Categories.CategoryRepository(_connectionString), new GameCollectiblesData.Games.GameRepository(_connectionString));
            _logger = logger;
        }

        public IActionResult Index([FromQuery] int categoryID)
        {
            return View();
        }

        public IActionResult Create([FromQuery]int CategoryID, [FromQuery]int GameID)
        {
            var model = new CollectibleViewModel{
                categoryID = CategoryID,
                gameID = GameID
            };
            return View(model);
        }

        public ActionResult AddCollectible(CollectibleViewModel collectibleVM)
        {
            Collectible collectible = new Collectible(collectibleVM.categoryID ?? default(int), collectibleVM.collectibleID ?? default(int), collectibleVM.collectibleName, collectibleVM.collectibleDescription, false)
            .setGameID(collectibleVM.gameID ?? default(int));

            _collectibleService.createCollectible(collectible);
            return RedirectToAction("Game", "Games", new { gameID = collectible.gameID });
        }

        


    }
}

GameCollectibles/GameCollectibleApp/Controllers/GamesController.cs
using GameCollectibleApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Data.Sql;
using GameCollectiblesCore.Games;
using GameCollectiblesData.Games;
using GameCollectiblesCore.Categories;
using GameCollectiblesData.Categories;
using GameCollectiblesCore.Collectibles;
using GameCollectiblesData.Collectibles;

namespace GameCollectibleApp.Controllers
{
    public class GamesController : Controller
    {
        private readonly string _connectionString;
        private readonly GameService _gameService;
        private readonly CategoryService _categoryService;
        private readonly CollectibleService _collectibleService;
        private readonly ILogger<HomeController> _logger;

        public GamesController(IConfiguration configuration, ILogger<HomeController> logger)
        {
            _connectionString = configuration.GetConnectionString("DefaultConnection");
            
            _gameService = new GameService(new GameCollectiblesData.Games.GameRepository(_connectionString));
            _categoryService = new CategoryService(new GameCollectiblesData.Categories.CategoryRepository(_connectionString), new GameCollectiblesData.Games.GameRepository(_connectionString));
            _collectibleService = new CollectibleService(new CollectibleRepository(_connectionString), new GameCollectiblesData.Categories.CategoryRepository(_connectionString), new GameCollectiblesData.Games.GameRepository(_connectionString));
            
            _logger = logger;
        }

        public IActionResult Index(string sortOrder)
        {
            try
            {
                var games = _gameService.GetAllGames();
                return View(games);
            }
            catch (SqlException)
            {
                var model = new GameErrorViewModel
                {
                    errorMessage = "Something went wrong with the connection to the database",
                };    
                return RedirectToAction("error", model);
            }
        }
        public IActionResult Create(GameViewModel model)
        {   
            return View(model);
        }
        [HttpPost]
        public IActionResult Delete([FromQuery] int gameID)
        {
            try
            {
                _gameService.DeleteGame(gameID);
                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                var model = new GameErrorViewModel
                {
                    errorMessage = ex.Message,
                };    
                return RedirectToAction("error", model);
            }
            
        }
        public ActionResult Edit([FromQuery] int gameID)
        {   
            try
            {
                var game = _gameService.GetGameByID(gameID);
                if (game == null)
                {
                    return NotFound();
                }
                return View(game);
            }
            catch (Exception ex)
            {
                var model = new GameErrorViewModel
                {
                    errorMessage = ex.Message,
                };    
                return RedirectToAction("error", model);
            }
        }
        
        [HttpPost]
        public ActionResult SubmitGame(GameViewModel gameVM)
        {
            Game game = new Game(gameVM.gameTitle)
            .setGameDescription(gameVM.gameDescription);
            try
            {
                _gameService.AddGame(game);
                return RedirectToAction("index");
            }
            catch (Exception ex)
            {

                var model = new GameViewModel
                {
                    errorMessage = ex.Message,
                };    
                return RedirectToAction("create", model);
            }
            
        }

        [HttpPost]
        public ActionResult EditGame(GameViewModel gameVM)
        {
            Game game = new Game(gameVM.gameTitle)
            .setGameDescription(gameVM.gameDescription)
            .setGameID(gameVM.gameID.GetValueOrDefault());
            try
            {
                if (ModelState.IsValid)
                {
                    _gameService.EditGame(game);
                    return RedirectToAction("index");
                }
                return RedirectToAction("game", game);
            }
            catch (Exception ex)
            {
                var model = new GameErrorViewModel
                {
                    errorMessage = ex.Message,
                };    
                return RedirectToAction("error", model);
            }
            
        }

        public IActionResult Game([FromQuery] int gameID)
        {
            try
            {
                int? currentUserID = HttpContext.Session.GetInt32("UserId");
                if (currentUserID == null)
                {
                    return RedirectToAction("index", "Users");
                }
                var _game = _gameService.GetGameByID(gameID);
                var categoriesWithoutCollectibles = _categoryService.GetCategories(gameID, currentUserID);
                var categoriesWithCollectibles = new List<Category>();

                foreach (var category in categoriesWithoutCollectibles)
                {
                    IEnumerable<Collectible> _collectibles = _collectibleService.GetCollectibles(category.categoryID, currentUserID);

                    category.setCollectibles(_collectibles);

                    categoriesWithCollectibles.Add(category);
                }

                

                if (_game == null)
                {
                    return RedirectToAction("error");
                }
                if (currentUserID == null)
                {
                    return NotFound();
                }
                var model = new GameViewModel
                {
                    game = _game,
                    categories = categoriesWithCollectibles,
                };
                return View(model);
            }
            catch (Exception ex)
            {
                var model = new GameErrorViewModel
                {
                    errorMessage = ex.Message,
                };    
                return RedirectToAction("error", model);
            }
            
        }

        

        public ActionResult ToggleCollected(int collectibleId, bool isToggledCollected, int categoryID, int gameId)
        {
            try
            {
                int? userId = HttpContext.Session.GetInt32("UserId");
                _collectibleService.ToggleCollected(collectibleId, isToggledCollected, userId, categoryID);
                return RedirectToAction("Game", new { gameID = gameId });
            }
            catch (Exception ex)
            {
                var model = new GameErrorViewModel
                {
                    errorMessage = ex.Message,
                };    
                return RedirectToAction("error", model);
            }

            
        }

        public IActionResult Error(GameErrorViewModel model)
        {
            return View(model);
        }

    }
}

GameCollectibles/GameCollectibleApp/Views/Games/Create.cshtml
@model GameViewModel
    
@{
    ViewData["Title"] = "Create Games";
}

<div class="ml-10 mt-10 flex-auto justify-center items-center">
    <form action="@Url.Action("SubmitGame", "Games")" method="post">
        <h1 class="text-red-500">@Model.errorMessage</h1>
        <br>
        <div class="mb-4 w-25 ">
            <label class="block text-gray-700 font-bold mb-2 flex justify-center" for="gameTitle">
                Game Name
            </label>
            <input class="flex justify-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="gameTitle" rows="2" placeholder="Enter game name">
        </div>
        <div class="mb-6 w-25">
            <label class="block text-gray-700 font-bold mb-2 flex justify-center" for="gameDescription">
                Game Description
            </label>
            <textarea class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="gameDescription" rows="2" placeholder="Enter game description"></textarea>
        </div>
        <div class="flex items-center justify-between mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                Add Game
            </button>
        </div>
    </form>
</div>

GameCollectibles/GameCollectibleApp/Views/Games/Delete.cshtml
@model IEnumerable<GameCollectiblesCore.Games.Game>
@{
	ViewData["Title"] = "Delete Games";
}

<div class="text-center">If you see this, something went wrong</div>

GameCollectibles/GameCollectibleApp/Views/Games/Edit.cshtml
@model GameCollectiblesCore.Games.Game
@{
	ViewData["Title"] = "Edit Games";
}

<div class="ml-10 mt-10 flex-auto justify-center items-center">
    <form action="@Url.Action("EditGame", "Games")" method="post"> 
        <div class="mb-4 w-25 ">
            <label class="block text-gray-700 font-bold mb-2 flex justify-center" for="gameTitle">
                Game Name
            </label>
            <input class="flex justify-center shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="gameTitle" rows="2" placeholder="" value="@Model.gameTitle">
        </div>
        <div class="mb-6 w-25">
            <label class="block text-gray-700 font-bold mb-2 flex justify-center" for="gameDescription">
                Game Description'
            </label>
            <textarea class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="gameDescription" rows="4" placeholder="">@Model.gameDescription</textarea>
        </div>
        <div class="flex items-center justify-between mt-4">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                Update
            </button>
        </div>
        <textarea class="invisible"name="gameID">@Model.gameID</textarea>
    </form>
</div>

GameCollectibles/GameCollectibleApp/Views/Games/Game.cshtml
@model GameCollectibleApp.Models.GameViewModel
@{
	ViewData["Title"] = "Game Details";
}
<style>
	.CrossCheck-size{
			width: 15px;
			height: 15px;
			margin-left: 15px;
		}

</style>


<div class="max-w-6xl w-full ml-20 ">
	<div class="text-center text-3xl mt-3">
		@Model.game.gameTitle
	</div>
	<div class="text-center text-xl">
		@Model.game.gameDescription
	</div>
	<div class="">
		<button class="py-2 px-4 bg-yellow-200 hover:bg-yellow-400 text-white font-semibold rounded-lg shadow-md transition duration-300" onclick="location.href='@Url.Action("Edit", "Games", new { gameID = Model.game.gameID })'">Edit</button>
		<form action="@Url.Action("Delete", "Games", new { gameID = Model.game.gameID })" method="post">
         	<input type="hidden" name="gameID" value="@Model.game.gameID" />
            <button class="py-2 px-4 bg-red-500 hover:bg-red-600 text-white font-semibold rounded-lg shadow-md transition duration-300" type="submit">Delete</button>
    	</form>
	</div>
	<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4 ">
    @foreach (var category in Model.categories)
    {
        <div class="bg-white shadow sm:rounded-lg">
            <div class="px-4 py-5 sm:px-6 bg-gray-50">
                <h3 class="text-lg leading-6 font-medium text-gray-900">@category.categoryName</h3>
            </div>
            <div class="border-t border-gray-200">
                <dl>
                    @foreach (var collectible in category.collectibles)
					{
						<p title="@collectible.collectibleDescription">
							@collectible.collectibleName
							@if (collectible.isCollected)
							{
								<input class="CrossCheck-size" type="image" src="~/images/greenCheckmark.png" onclick="location.href='@Url.Action("ToggleCollected", "Games")?collectibleID=@collectible.collectibleID&isToggledCollected=@collectible.isCollected&categoryID=@category.categoryID&gameId=@Model.game.gameID'" /> 
							}
							else
							{
								<input class="CrossCheck-size" type="image" src="~/images/redX.png" onclick="location.href='@Url.Action("ToggleCollected", "Games")?collectibleID=@collectible.collectibleID&isToggledCollected=@collectible.isCollected&categoryID=@category.categoryID&gameId=@Model.game.gameID'" /> 
							}
							
						</p>
						
					}
					
                    <button class="h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800" onclick="location.href='@Url.Action("Create", "Collectibles", new { categoryID = category.categoryID, gameID = @Model.game.gameID })'">Add Collectible</button>
                </dl>
            </div>
        </div>
    }
    <button class="h-8 px-4 m-2 text-sm text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800" onclick="location.href='@Url.Action("Create", "Categories", new { gameID = Model.game.gameID})'">Create Category</button>
</div>
</div>

GameCollectibles/GameCollectibleApp/Views/Games/Index.cshtml
@model IEnumerable<GameCollectiblesCore.Games.Game>
@{
	ViewData["Title"] = "Game List";
}

<div class="max-w-6xl w-full ml-20 ">
    <div class="h-screen overflow-y-auto">
        <div class="grid grid-cols-3 gap-4 mt-8 mb-8">
            @foreach (var game in Model)
            {
                <div class="bg-white shadow-md rounded-lg px-4 py-6 flex flex-col w-128 h-64">
                    <h2 class="text-lg font-bold mb-4">@game.gameTitle</h2>
                    <p class="text-gray-700 mb-2">@game.gameDescription</p>
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 rounded mt-auto" onclick="location.href='@Url.Action("Game", "Games", new { gameID = game.gameID })'">Go To Game</button>
                </div>
            }
            <div class="">
                <input type="button" class="bg-blue-500 text-white shadow-md rounded-lg px-4 py-6 w-64 h-64 hover:bg-blue-900 text-4xl" value="Create" onclick="location.href='@Url.Action("Create", "Games")'" />
            </div>
        </div>
    </div>
</div>